/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type RichTextSimple = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal';
  listItem?: never;
  markDefs?: Array<{
    href?: string;
    _type: 'link';
    _key: string;
  }>;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type RichTextBase = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: 'span';
    _key: string;
  }>;
  style?: 'normal';
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: 'block';
  _key: string;
}>;

export type CollectionReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'collection';
};

export type Homepage = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  features: Array<{
    collection: CollectionReference;
    slides: Array<{
      images: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      _type: 'Slide';
      _key: string;
    }>;
    _type: 'Feature';
    _key: string;
  }>;
};

export type ProjectReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'project';
};

export type Collection = {
  _id: string;
  _type: 'collection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  metadata?: {
    description?: RichTextSimple;
    keywords?: Array<string>;
  };
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  year?: number;
  location?: string;
  client?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  projectType: 'personal' | 'commissioned';
  description?: RichTextSimple;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  metadata?: {
    description?: RichTextSimple;
    keywords?: Array<string>;
  };
};

export type Info = {
  _id: string;
  _type: 'info';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  description?: RichTextSimple;
  education?: Array<{
    item?: RichTextSimple;
    _type: 'education';
    _key: string;
  }>;
  groupShows?: Array<{
    name?: RichTextSimple;
    _type: 'groupShow';
    _key: string;
  }>;
  pressItems?: Array<{
    title?: RichTextSimple;
    href?: string;
    _type: 'press';
    _key: string;
  }>;
  contact?: RichTextSimple;
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | RichTextSimple
  | RichTextBase
  | CollectionReference
  | Homepage
  | ProjectReference
  | Collection
  | Slug
  | Project
  | Info
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../www/lib/sanity/queries.ts
// Variable: INDEX_PROJECTS_QUERY
// Query: *[_type == "project"] | order(year desc) {   ...,  images[] {      ...,  asset -> {    ...  }  },  coverImage {      ...,  asset -> {    ...  }  },  description[] {      ...,  markDefs[] {    ...,  }  } }
export type INDEX_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  year?: number;
  location?: string;
  client?: string;
  images: Array<{
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }> | null;
  projectType: 'commissioned' | 'personal';
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }> | null;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  coverImage: {
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  metadata?: {
    description?: RichTextSimple;
    keywords?: Array<string>;
  };
}>;

// Source: ../www/lib/sanity/queries.ts
// Variable: GET_PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {   ...,  images[] {      ...,  asset -> {    ...  }  },  coverImage {      ...,  asset -> {    ...  }  },  description[] {      ...,  markDefs[] {    ...,  }  } }
export type GET_PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  year?: number;
  location?: string;
  client?: string;
  images: Array<{
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }> | null;
  projectType: 'commissioned' | 'personal';
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }> | null;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  coverImage: {
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  metadata?: {
    description?: RichTextSimple;
    keywords?: Array<string>;
  };
} | null;

// Source: ../www/lib/sanity/queries.ts
// Variable: GET_SETTINGS_QUERY
// Query: *[_type == "settings" && _id == "settings"][0] {   ... }
export type GET_SETTINGS_QUERY_RESULT = {
  _id: 'settings';
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
} | null;

// Source: ../www/lib/sanity/queries.ts
// Variable: GET_INFO_QUERY
// Query: *[_type == "info" && _id == "info"][0] {   ...,  coverImage {      ...,  asset -> {    ...  }  } }
export type GET_INFO_QUERY_RESULT = {
  _id: 'info';
  _type: 'info';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  description?: RichTextSimple;
  education?: Array<{
    item?: RichTextSimple;
    _type: 'education';
    _key: string;
  }>;
  groupShows?: Array<{
    name?: RichTextSimple;
    _type: 'groupShow';
    _key: string;
  }>;
  pressItems?: Array<{
    title?: RichTextSimple;
    href?: string;
    _type: 'press';
    _key: string;
  }>;
  contact?: RichTextSimple;
  coverImage: null;
} | null;

// Source: ../www/lib/sanity/queries.ts
// Variable: GET_COLLECTION_BY_SLUG_QUERY
// Query: *[_type == "collection" && slug.current == $slug][0] {   ...,  projects[] -> {      ...,  images[] {      ...,  asset -> {    ...  }  },  coverImage {      ...,  asset -> {    ...  }  },  description[] {      ...,  markDefs[] {    ...,  }  }  },  coverImage {      ...,  asset -> {    ...  }  } }
export type GET_COLLECTION_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: 'collection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  projects: Array<{
    _id: string;
    _type: 'project';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    year?: number;
    location?: string;
    client?: string;
    images: Array<{
      asset: {
        _id: string;
        _type: 'sanity.imageAsset';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }> | null;
    projectType: 'commissioned' | 'personal';
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal';
      listItem?: never;
      markDefs: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }> | null;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    coverImage: {
      asset: {
        _id: string;
        _type: 'sanity.imageAsset';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    metadata?: {
      description?: RichTextSimple;
      keywords?: Array<string>;
    };
  }> | null;
  coverImage: {
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  metadata?: {
    description?: RichTextSimple;
    keywords?: Array<string>;
  };
} | null;

// Source: ../www/lib/sanity/queries.ts
// Variable: INDEX_COLLECTIONS_QUERY
// Query: *[_type == "collection"] | order(title asc) {   ...,  projects[] -> {      ...,  images[] {      ...,  asset -> {    ...  }  },  coverImage {      ...,  asset -> {    ...  }  },  description[] {      ...,  markDefs[] {    ...,  }  }  },  coverImage {      ...,  asset -> {    ...  }  } }
export type INDEX_COLLECTIONS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'collection';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  projects: Array<{
    _id: string;
    _type: 'project';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title: string;
    slug: Slug;
    year?: number;
    location?: string;
    client?: string;
    images: Array<{
      asset: {
        _id: string;
        _type: 'sanity.imageAsset';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
      _key: string;
    }> | null;
    projectType: 'commissioned' | 'personal';
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal';
      listItem?: never;
      markDefs: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }> | null;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
    coverImage: {
      asset: {
        _id: string;
        _type: 'sanity.imageAsset';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    metadata?: {
      description?: RichTextSimple;
      keywords?: Array<string>;
    };
  }> | null;
  coverImage: {
    asset: {
      _id: string;
      _type: 'sanity.imageAsset';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  metadata?: {
    description?: RichTextSimple;
    keywords?: Array<string>;
  };
}>;

// Source: ../www/lib/sanity/queries.ts
// Variable: GET_HOMEPAGE_QUERY
// Query: *[_type == "homepage" && _id == "homepage"][0] {   ...,  features[] {      ...,  slides[] {      ...,  images[] {      ...,  asset -> {    ...  }  }  },  collection -> {      ...,  projects[] -> {      ...,  images[] {      ...,  asset -> {    ...  }  },  coverImage {      ...,  asset -> {    ...  }  },  description[] {      ...,  markDefs[] {    ...,  }  }  },  coverImage {      ...,  asset -> {    ...  }  }  }  } }
export type GET_HOMEPAGE_QUERY_RESULT = {
  _id: 'homepage';
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  features: Array<{
    collection: {
      _id: string;
      _type: 'collection';
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title: string;
      slug: Slug;
      projects: Array<{
        _id: string;
        _type: 'project';
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        title: string;
        slug: Slug;
        year?: number;
        location?: string;
        client?: string;
        images: Array<{
          asset: {
            _id: string;
            _type: 'sanity.imageAsset';
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash: string;
            extension: string;
            mimeType: string;
            size: number;
            assetId: string;
            uploadId?: string;
            path: string;
            url: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: 'image';
          _key: string;
        }> | null;
        projectType: 'commissioned' | 'personal';
        description: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'normal';
          listItem?: never;
          markDefs: Array<{
            href?: string;
            _type: 'link';
            _key: string;
          }> | null;
          level?: number;
          _type: 'block';
          _key: string;
        }> | null;
        coverImage: {
          asset: {
            _id: string;
            _type: 'sanity.imageAsset';
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            originalFilename?: string;
            label?: string;
            title?: string;
            description?: string;
            altText?: string;
            sha1hash: string;
            extension: string;
            mimeType: string;
            size: number;
            assetId: string;
            uploadId?: string;
            path: string;
            url: string;
            metadata?: SanityImageMetadata;
            source?: SanityAssetSourceData;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: 'image';
        } | null;
        metadata?: {
          description?: RichTextSimple;
          keywords?: Array<string>;
        };
      }> | null;
      coverImage: {
        asset: {
          _id: string;
          _type: 'sanity.imageAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash: string;
          extension: string;
          mimeType: string;
          size: number;
          assetId: string;
          uploadId?: string;
          path: string;
          url: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      } | null;
      metadata?: {
        description?: RichTextSimple;
        keywords?: Array<string>;
      };
    };
    slides: Array<{
      images: Array<{
        asset: {
          _id: string;
          _type: 'sanity.imageAsset';
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash: string;
          extension: string;
          mimeType: string;
          size: number;
          assetId: string;
          uploadId?: string;
          path: string;
          url: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }>;
      _type: 'Slide';
      _key: string;
    }>;
    _type: 'Feature';
    _key: string;
  }>;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "project"] | order(year desc) { \n  ...,\n  images[] {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  description[] {\n    \n  ...,\n  markDefs[] {\n    ...,\n  }\n\n  }\n }': INDEX_PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0] { \n  ...,\n  images[] {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  description[] {\n    \n  ...,\n  markDefs[] {\n    ...,\n  }\n\n  }\n }': GET_PROJECT_BY_SLUG_QUERY_RESULT;
    '*[_type == "settings" && _id == "settings"][0] { \n  ...\n }': GET_SETTINGS_QUERY_RESULT;
    '*[_type == "info" && _id == "info"][0] { \n  ...,\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  }\n }': GET_INFO_QUERY_RESULT;
    '*[_type == "collection" && slug.current == $slug][0] { \n  ...,\n  projects[] -> {\n    \n  ...,\n  images[] {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  description[] {\n    \n  ...,\n  markDefs[] {\n    ...,\n  }\n\n  }\n\n  },\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  }\n }': GET_COLLECTION_BY_SLUG_QUERY_RESULT;
    '*[_type == "collection"] | order(title asc) { \n  ...,\n  projects[] -> {\n    \n  ...,\n  images[] {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  description[] {\n    \n  ...,\n  markDefs[] {\n    ...,\n  }\n\n  }\n\n  },\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  }\n }': INDEX_COLLECTIONS_QUERY_RESULT;
    '*[_type == "homepage" && _id == "homepage"][0] { \n  ...,\n  features[] {\n    \n  ...,\n  slides[] {\n    \n  ...,\n  images[] {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  }\n\n  },\n  collection -> {\n    \n  ...,\n  projects[] -> {\n    \n  ...,\n  images[] {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  },\n  description[] {\n    \n  ...,\n  markDefs[] {\n    ...,\n  }\n\n  }\n\n  },\n  coverImage {\n    \n  ...,\n  asset -> {\n    ...\n  }\n\n  }\n\n  }\n\n  }\n }': GET_HOMEPAGE_QUERY_RESULT;
  }
}
